spring.application.name=Backend

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:C:\\Projects\\NTT-DATA-Assignments\\Backend\\src\\main\\resources\\sql\\database;AUTO_SERVER=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.sql.init.schema-locations=file:C:\\Projects\\NTT-DATA-Assignments\\Backend\\src\\main\\resources\\sql\\database-schema.sql
spring.jpa.show-sql=${SHOW_SQL:true}