spring.application.name=Student Task Manager Assignment

spring.datasource.url=jdbc:postgresql://localhost:5432/nttstudents
spring.datasource.username=ntt
spring.datasource.password=ntt
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.docker.compose.lifecycle-management=start-and-stop
spring.docker.compose.file=./Student Task Manager Assignment/compose.yaml